name:                climate-crisis-monads
version:             0.1.0.0
homepage:            https://github.com/silky/solving-climate-crisis-monads
license:             BSD3
author:              Noon van der Silk
maintainer:          noonsilk@gmail.com
copyright:           2022 Noon van der Silk
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - data-default
  - net-mqtt
  - network-uri
  - text
  - transformers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - ImportQualifiedPost
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators

executables:
  climate-crisis-monads:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
      - -threaded
